### ISSUE TITLE
Issue when converting Arcane model 

### ISSUE THREAD

**Issue by kyhoolee** [juanjaho/animeGAN_Mobile#2] opened 2022-05-26 06:26 UTC
Hi, I use your code snippet to convert model 
https://github.com/juanjaho/AnimeArcaneGAN_Mobile/issues/1 
The model from Arcane notebook 
https://colab.research.google.com/drive/1r1hhciakk5wHaUn1eJk7TP58fV9mjy_W#scrollTo=vTK5g1xio5oe

```import torch
from torch.utils.mobile_optimizer import optimize_for_mobile
from torchvision import transforms
from PIL import Image


v = '0.3' 

model_path = f'/content/ArcaneGANv{version}.jit' 

model = torch.jit.load(model_path, map_location="cpu").to('cpu').float().eval().cpu()
image = Image.open("/content/in/5.jpg").convert("RGB")


means = [0.485, 0.456, 0.406]
stds = [0.229, 0.224, 0.225]

img_transforms = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(means, stds)])

with torch.no_grad():
    image = img_transforms(image)[None, ...].cpu().float()
    traced_script_module = torch.jit.trace(model, image)
    optimized_traced_model = optimize_for_mobile(traced_script_module)
    optimized_traced_model._save_for_lite_interpreter(f"/content/drive/MyDrive/FloatArcaneGAN{v}.ptl")
```

But when I load model in android - I got this issue 

```   
com.facebook.jni.CppException: expected scalar type Float but found Half
      
      Debug info for handle(s): -1, was not found.
      
    Exception raised from data_ptr at aten/src/ATen/core/TensorMethods.cpp:18 (most recent call first):
```

I see that your code converts the model parameters to float, but it is still error.
Can you try again with the Arcane JIT model from the notebook and test the result on android again

**Comment by juanjaho** [comment] 2022-05-28 14:00
Hello,

This issue is likely due to the .jit model having a hard coded data types, explained by Alex himself [here](https://github.com/Sxela/ArcaneGAN/issues/1#issuecomment-1042828110)

The data types being hard coded onto the model and _.half_ data type not being supported on CPU was part of the reason that I kept to the ArcaneGAN v0.3 model which uses _.float_ data type and compatible with CPU. 

However, you may try the solution this guy uses [here](https://github.com/Sxela/ArcaneGAN/issues/1#issuecomment-1044793008). I have yet to test it, but do update us here if it works.

References: https://github.com/Sxela/ArcaneGAN/issues/1
ArcaneGANv0.3 (cpu compatible): https://github.com/Sxela/ArcaneGAN/releases/download/v0.3/ArcaneGANv0.3.jit

**Comment by kyhoolee** [comment] 2022-07-07 09:45
Thank for your reply,
I tried the solution from Alex's repo, but it still not work 
https://github.com/Sxela/ArcaneGAN/issues/1#issuecomment-1042828110

**Comment by juanjaho** [comment] 2023-01-04 09:43
The cause of the Issue has been identified as inherent model incompatibility. Closing Issue here.

**Closed as completed by juanjaho** 2023-01-04 09:43 UTC
